_wandb:
    value:
        cli_version: 0.24.0
        e:
            zvqpif722dn0uveq2y24tm841p4fp634:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                args:
                    - --pipeline
                    - all
                    - --config
                    - configs/config.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "464450678784"
                email: mathias.krois@gmail.com
                executable: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops-project-group34/.venv/bin/python3
                git:
                    commit: 9e995d65760279d3fd26a95aa41a1c88d6c182d6
                    remote: https://github.com/MLOPS-Group34/mlops-project-group34.git
                host: Mathiass-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops-project-group34/main.py
                python: CPython 3.11.5
                root: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops-project-group34
                startedAt: "2026-01-16T09:18:52.584952Z"
                writerId: zvqpif722dn0uveq2y24tm841p4fp634
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.5
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
data_sampling:
    value:
        enabled: true
        random_seed: 42
        test_samples: 50
        train_samples: 500
        val_samples: 100
hyperparameters:
    value:
        batch_size: 32
        classes:
            "0": fire
            "1": smoke
        epochs: 5
        img_size: 640
        lr: 0.01
        model_type: yolov8n.pt
paths:
    value:
        logs_dir: logs
        models_dir: models
        reports_dir: reports/figures
        root_dir: ../
        test_images: data/processed/test/images
        test_labels: data/processed/test/labels
        train_images: data/processed/train/images
        train_labels: data/processed/train/labels
        val_images: data/processed/val/images
        val_labels: data/processed/val/labels
        yolo_yaml: data.yaml
project_name:
    value: forest_fire_detection
wandb_project:
    value: mlops_project_group34
