[theme]
primaryColor = "#FF0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[server]
headless = true
port = 8501
baseUrlPath = ""
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
